# Generated by Django 4.0.5 on 2022-12-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=20)),
                ('disease', models.CharField(max_length=50)),
            ],
        ),
    ]
