# Generated by Django 4.0.5 on 2023-05-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yoga_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='lastname',
            new_name='pass1',
        ),
        migrations.AddField(
            model_name='members',
            name='pass2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
