# Generated by Django 4.0.5 on 2023-05-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yoga_App', '0002_rename_firstname_members_fullname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yogas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media/')),
                ('description', models.CharField(max_length=255)),
                ('usedfor', models.CharField(max_length=255)),
            ],
        ),
    ]
