# Generated by Django 4.0.5 on 2023-05-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yoga_App', '0004_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='status',
            field=models.CharField(default='In Progress', max_length=20),
        ),
    ]
