# Generated by Django 4.0.5 on 2023-05-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yoga_App', '0005_contactus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
