# Generated by Django 4.0.5 on 2023-05-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yoga_App', '0006_alter_members_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
