# Generated by Django 4.0.5 on 2023-05-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yoga_App', '0007_alter_contactus_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('d_code', models.CharField(max_length=10)),
                ('d_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='ContactTable',
        ),
        migrations.RenameModel(
            old_name='Members',
            new_name='MemberTable',
        ),
        migrations.RenameModel(
            old_name='Yogas',
            new_name='YogaTable',
        ),
    ]
