# Generated by Django 4.0.5 on 2023-05-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yoga_App', '0008_diseasetable_rename_contactus_contacttable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yogatable',
            old_name='description',
            new_name='benefits',
        ),
        migrations.RenameField(
            model_name='yogatable',
            old_name='usedfor',
            new_name='how_to_do',
        ),
        migrations.AddField(
            model_name='yogatable',
            name='used_for',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yogatable',
            name='y_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yogatable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='yogatable',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
