# Generated by Django 4.0.5 on 2023-05-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yoga_App', '0009_rename_description_yogatable_benefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogatable',
            name='disease_code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yogatable',
            name='image',
            field=models.FileField(upload_to='static/img'),
        ),
    ]
