# Generated by Django 4.0.5 on 2023-05-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yoga_App', '0011_alter_yogatable_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yogatable',
            name='used_for',
        ),
    ]
