# Generated by Django 4.0.5 on 2023-05-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yoga_App', '0012_remove_yogatable_used_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogatable',
            name='benefits',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='yogatable',
            name='disease_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='yogatable',
            name='how_to_do',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='yogatable',
            name='image',
            field=models.ImageField(upload_to='media/img/'),
        ),
        migrations.AlterField(
            model_name='yogatable',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='yogatable',
            name='y_code',
            field=models.CharField(max_length=5),
        ),
    ]
