# Generated by Django 4.0.5 on 2023-05-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yoga_App', '0013_alter_yogatable_benefits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogatable',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
