# Generated by Django 4.0.5 on 2023-05-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yoga_App', '0015_alter_yogatable_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasetable',
            name='image',
            field=models.ImageField(default=1, upload_to='static/img/'),
            preserve_default=False,
        ),
    ]
