# Generated by Django 4.0.5 on 2023-05-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yoga_App', '0016_diseasetable_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogatable',
            name='video',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
