# Generated by Django 4.2 on 2023-05-13 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yoga_App', '0018_remove_yogatable_video_yogatable_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yogatable',
            name='y_code',
        ),
    ]
