# Generated by Django 4.0.5 on 2023-05-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yoga_App', '0019_remove_yogatable_y_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogatable',
            name='benefits',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='yogatable',
            name='how_to_do',
            field=models.TextField(max_length=1500),
        ),
    ]
