# Generated by Django 4.0.5 on 2023-05-15 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Yoga_App', '0020_alter_yogatable_benefits_alter_yogatable_how_to_do'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogatable',
            name='contraindications',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
